import Link from "next/link";
import { notFound } from "next/navigation";
import { updateBusinessAsAdmin, updateProfessionalAsAdmin, updateServiceAsAdmin } from "@/app/admin/actions";
import { Notice } from "@/components/notice";
import { SubmitButton } from "@/components/submit-button";
import { createClient } from "@/lib/supabase/server";
import { formatCurrency, formatDateTime } from "@/lib/format";

export default async function AdminBusinessDetailPage({ params, searchParams }: { params: Promise<{ businessId: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { businessId } = await params; const supabase = await createClient();
  const [businessResult, professionalsResult, servicesResult, membersResult, customersResult, appointmentsResult, hoursResult, auditResult] = await Promise.all([
    supabase.from("businesses").select("*").eq("id", businessId).maybeSingle(),
    supabase.from("professionals").select("id,name,photo_url,bio,active,user_id,setup_completed_at").eq("business_id", businessId).order("name"),
    supabase.from("services").select("id,name,description,price_cents,default_duration_minutes,active").eq("business_id", businessId).order("name"),
    supabase.from("business_members").select("id,user_id,role,created_at").eq("business_id", businessId),
    supabase.from("customers").select("id,name,phone").eq("business_id", businessId).order("created_at", { ascending: false }).limit(20),
    supabase.from("appointments").select("id,starts_at,status,customers(name),services(name),professionals(name)").eq("business_id", businessId).order("starts_at", { ascending: false }).limit(20),
    supabase.from("working_hours").select("id,professional_id,weekday,start_time,end_time,active").eq("business_id", businessId).order("weekday"),
    supabase.from("admin_audit_logs").select("id,action,entity_type,created_at,metadata").eq("business_id", businessId).order("created_at", { ascending: false }).limit(20),
  ]);
  const business = businessResult.data; if (!business) notFound();
  return <><header className="page-header"><div><p className="eyebrow">Empresa / {business.slug}</p><h1>{business.name}</h1><p className="muted">{business.active ? "Empresa ativa" : "Empresa inativa"} · {business.timezone}</p></div><Link className="button-ghost" href={`/${business.slug}`} target="_blank">Abrir página pública</Link></header><Notice {...await searchParams} />
    <section className="panel-card"><h2>Dados da empresa</h2><form action={updateBusinessAsAdmin} className="form-stack"><input type="hidden" name="business_id" value={business.id} /><div className="field-grid"><label>Nome<input name="name" defaultValue={business.name} required /></label><label>Telefone<input name="phone" defaultValue={business.phone} required /></label><label>Fuso horário<input name="timezone" defaultValue={business.timezone} required /></label><label>Logo URL<input name="logo_url" type="url" defaultValue={business.logo_url ?? ""} /></label></div><label className="check"><input type="checkbox" name="active" defaultChecked={business.active} /> Empresa ativa</label><SubmitButton>Salvar empresa</SubmitButton></form></section>
    <div className="split-grid top-gap"><section className="panel-card"><h2>Profissionais ({professionalsResult.data?.length ?? 0})</h2>{(professionalsResult.data ?? []).map((professional) => <details className="edit-details admin-edit" key={professional.id}><summary>{professional.name} · {professional.active ? "ativo" : "inativo"}</summary><form action={updateProfessionalAsAdmin} className="form-stack compact"><input type="hidden" name="business_id" value={business.id} /><input type="hidden" name="professional_id" value={professional.id} /><label>Nome<input name="name" defaultValue={professional.name} required /></label><label>Foto URL<input name="photo_url" type="url" defaultValue={professional.photo_url ?? ""} /></label><label>Bio<textarea name="bio" defaultValue={professional.bio ?? ""} /></label><label className="check"><input type="checkbox" name="active" defaultChecked={professional.active} /> Ativo</label><small>{professional.setup_completed_at ? "Configuração concluída" : "Configuração pendente"} · {hoursResult.data?.filter((hour) => hour.professional_id === professional.id && hour.active).length ?? 0} faixas</small><SubmitButton className="button-ghost">Salvar profissional</SubmitButton></form></details>)}</section>
      <section className="panel-card"><h2>Serviços ({servicesResult.data?.length ?? 0})</h2>{(servicesResult.data ?? []).map((service) => <details className="edit-details admin-edit" key={service.id}><summary>{service.name} · {formatCurrency(service.price_cents)}</summary><form action={updateServiceAsAdmin} className="form-stack compact"><input type="hidden" name="business_id" value={business.id} /><input type="hidden" name="service_id" value={service.id} /><label>Nome<input name="name" defaultValue={service.name} required /></label><label>Descrição<textarea name="description" defaultValue={service.description ?? ""} /></label><div className="field-grid"><label>Preço (R$)<input name="price" type="number" min="0" step="0.01" defaultValue={(service.price_cents / 100).toFixed(2)} /></label><label>Duração<input name="duration" type="number" min="5" step="5" defaultValue={service.default_duration_minutes} /></label></div><label className="check"><input type="checkbox" name="active" defaultChecked={service.active} /> Ativo</label><SubmitButton className="button-ghost">Salvar serviço</SubmitButton></form></details>)}</section></div>
    <div className="split-grid top-gap"><section className="panel-card"><h2>Clientes recentes</h2><div className="list">{(customersResult.data ?? []).map((customer) => <article className="list-row" key={customer.id}><strong>{customer.name}</strong><span>{customer.phone}</span></article>)}</div></section><section className="panel-card"><h2>Membros ({membersResult.data?.length ?? 0})</h2><div className="list">{(membersResult.data ?? []).map((member) => <article className="list-row" key={member.id}><div><strong>{member.role}</strong><p>{member.user_id}</p></div><small>{formatDateTime(member.created_at, business.timezone)}</small></article>)}</div></section></div>
    <section className="panel-card top-gap"><h2>Agendamentos recentes</h2><div className="list">{(appointmentsResult.data ?? []).map((appointment) => <article className="list-row" key={appointment.id}><div><strong>{formatDateTime(appointment.starts_at, business.timezone)}</strong><p>{(appointment.customers as unknown as { name: string } | null)?.name} · {(appointment.services as unknown as { name: string } | null)?.name}</p></div><span>{(appointment.professionals as unknown as { name: string } | null)?.name} · {appointment.status}</span></article>)}</div></section>
    <section className="panel-card top-gap"><h2>Auditoria administrativa</h2>{!auditResult.data?.length ? <p className="empty">Nenhuma alteração administrativa registrada.</p> : <div className="list">{auditResult.data.map((log) => <article className="list-row" key={log.id}><div><strong>{log.action}</strong><p>{log.entity_type}</p></div><small>{formatDateTime(log.created_at, business.timezone)}</small></article>)}</div>}</section></>;
}
