import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { formatDateTime } from "@/lib/format";

export default async function AdminDashboardPage() {
  const supabase=await createClient(); const today=new Date(); today.setHours(0,0,0,0); const monthAgo=new Date(today); monthAgo.setDate(monthAgo.getDate()-30);
  const [businesses,activeBusinesses,users,professionals,customers,appointments,todayAppointments,newBusinesses,recent,recentAppointments]=await Promise.all([
    supabase.from("businesses").select("id",{count:"exact",head:true}),supabase.from("businesses").select("id",{count:"exact",head:true}).eq("active",true),supabase.from("login_identities").select("id",{count:"exact",head:true}),supabase.from("professionals").select("id",{count:"exact",head:true}),supabase.from("customers").select("id",{count:"exact",head:true}),supabase.from("appointments").select("id",{count:"exact",head:true}),supabase.from("appointments").select("id",{count:"exact",head:true}).gte("starts_at",today.toISOString()),supabase.from("businesses").select("id",{count:"exact",head:true}).gte("created_at",monthAgo.toISOString()),supabase.from("businesses").select("id,name,slug,active,created_at").order("created_at",{ascending:false}).limit(6),supabase.from("appointments").select("id,starts_at,status,businesses(name,timezone),customers(name),professionals(name)").order("created_at",{ascending:false}).limit(6)
  ]);
  const stats=[["Estabelecimentos",businesses.count],["Estabelecimentos ativos",activeBusinesses.count],["Usuários",users.count],["Profissionais",professionals.count],["Clientes",customers.count],["Agendamentos",appointments.count],["Agendamentos de hoje",todayAppointments.count],["Novos estabelecimentos",newBusinesses.count]];
  return <><header className="page-header"><div><p className="eyebrow">NEXO ADMIN</p><h1>Visão geral da plataforma</h1><p className="muted">Agenda inteligente para negócios e profissionais.</p></div><Link className="button" href="/admin/empresas/nova">Novo estabelecimento</Link></header><section className="stat-grid admin-stats">{stats.map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value??0}</strong></article>)}</section><div className="split-grid"><section className="panel-card"><div className="section-title"><h2>Últimos estabelecimentos</h2><Link href="/admin/empresas">Ver todos</Link></div><div className="list">{(recent.data??[]).map((business)=><Link className="list-row" href={`/admin/empresas/${business.id}`} key={business.id}><div><strong>{business.name}</strong><p>/{business.slug}</p></div><div className="align-right"><span className={business.active?"status-active":"status-inactive"}>{business.active?"Ativo":"Inativo"}</span><small>{formatDateTime(business.created_at,"America/Sao_Paulo")}</small></div></Link>)}</div></section><section className="panel-card"><div className="section-title"><h2>Agendamentos recentes</h2><Link href="/admin/agendamentos">Ver todos</Link></div><div className="list">{(recentAppointments.data??[]).map((appointment)=>{const business=appointment.businesses as unknown as {name:string;timezone:string}|null;return <article className="list-row" key={appointment.id}><div><strong>{(appointment.customers as unknown as {name:string}|null)?.name}</strong><p>{business?.name}</p></div><div className="align-right"><span>{formatDateTime(appointment.starts_at,business?.timezone??"America/Sao_Paulo")}</span><small>{(appointment.professionals as unknown as {name:string}|null)?.name} · {appointment.status}</small></div></article>})}</div></section></div></>;
}
