"use client";

import { useActionState, useMemo, useState } from "react";
import Link from "next/link";
import { createBusinessAsAdmin, type CreateBusinessState } from "@/app/admin/actions";

type UserInput = { name: string; username: string; password: string; role: "OWNER" | "PROFESSIONAL"; is_professional: boolean; photo_url: string; active: boolean };
type ServiceInput = { name: string; price: string; duration_minutes: number };
const initialState: CreateBusinessState = {};
const categories = [["BARBERSHOP","Barbearia"],["SALON","Salão de beleza"],["AESTHETICS","Estética"],["CLINIC","Clínica"],["OFFICE","Consultório"],["TATTOO","Tatuagem"],["MANICURE","Manicure"],["PERSONAL_TRAINER","Personal trainer"],["PET_SERVICE","Pet / banho e tosa"],["MASSAGE","Massagem"],["STUDIO","Studio"],["CONSULTING","Consultoria"],["OTHER","Outro"]];
function password() { const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%"; const bytes = crypto.getRandomValues(new Uint8Array(18)); return Array.from(bytes, (byte) => chars[byte % chars.length]).join(""); }

export function NewBusinessWizard() {
  const [state, action, pending] = useActionState(createBusinessAsAdmin, initialState); const [step, setStep] = useState(1);
  const [business, setBusiness] = useState({ name: "", business_type: "OTHER", slug: "", phone: "", timezone: "America/Sao_Paulo", logo_url: "" });
  const [users, setUsers] = useState<UserInput[]>([{ name: "", username: "", password: password(), role: "OWNER", is_professional: true, photo_url: "", active: true }]);
  const [services, setServices] = useState<ServiceInput[]>([{ name: "", price: "", duration_minutes: 60 }]);
  const payload = useMemo(() => ({ business, users, services: services.map((service) => ({ name: service.name, price_cents: Math.round(Number(service.price.replace(",", ".")) * 100), duration_minutes: Number(service.duration_minutes) })) }), [business, users, services]);
  const updateUser = (index: number, patch: Partial<UserInput>) => setUsers(users.map((user, item) => item === index ? { ...user, ...patch } : user));
  const updateService = (index: number, patch: Partial<ServiceInput>) => setServices(services.map((service, item) => item === index ? { ...service, ...patch } : service));
  if (state.credentials) return <section className="panel-card credential-result"><p className="eyebrow">Estabelecimento criado</p><h2>Salve estas credenciais agora</h2><p>As senhas não poderão ser consultadas novamente.</p>{state.credentials.map((credential) => <div className="credential-row" key={credential.username}><strong>{credential.label}</strong><code>{credential.username}</code><code>{credential.password}</code></div>)}<Link className="button" href={`/admin/empresas/${state.businessId}`}>Abrir estabelecimento</Link></section>;
  return <section className="panel-card wizard-card"><div className="wizard-progress">{[1,2,3,4].map((number) => <span className={number <= step ? "active" : ""} key={number}>{number}</span>)}</div>
    {state.error && <p className="notice notice-error">{state.error}</p>}
    {step === 1 && <div><p className="eyebrow">1. Estabelecimento</p><h2>Dados públicos</h2><div className="form-stack"><div className="field-grid"><label>Nome<input value={business.name} onChange={(e) => setBusiness({ ...business, name: e.target.value, slug: business.slug || e.target.value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") })} /></label><label>Categoria<select value={business.business_type} onChange={(e) => setBusiness({ ...business, business_type: e.target.value })}>{categories.map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Slug<input value={business.slug} onChange={(e) => setBusiness({ ...business, slug: e.target.value.toLowerCase() })} /></label><label>WhatsApp<input value={business.phone} onChange={(e) => setBusiness({ ...business, phone: e.target.value })} /></label><label>Timezone<input value={business.timezone} onChange={(e) => setBusiness({ ...business, timezone: e.target.value })} /></label><label>Logo URL<input type="url" value={business.logo_url} onChange={(e) => setBusiness({ ...business, logo_url: e.target.value })} /></label></div></div></div>}
    {step === 2 && <div><p className="eyebrow">2. Acessos</p><h2>Dono e profissionais</h2>{users.map((user,index) => <div className="repeater-card" key={index}><div className="field-grid"><label>Nome<input value={user.name} onChange={(e) => updateUser(index,{name:e.target.value})} /></label><label>Username<input value={user.username} onChange={(e) => updateUser(index,{username:e.target.value.toLowerCase()})} /></label><label>Senha temporária<div className="input-action"><input value={user.password} onChange={(e) => updateUser(index,{password:e.target.value})} /><button type="button" className="button-ghost" onClick={() => updateUser(index,{password:password()})}>Gerar</button></div></label><label>Role<select value={user.role} disabled={index===0} onChange={(e) => updateUser(index,{role:e.target.value as UserInput["role"]})}><option value="OWNER">OWNER</option><option value="PROFESSIONAL">PROFESSIONAL</option></select></label><label>Foto URL<input type="url" value={user.photo_url} onChange={(e) => updateUser(index,{photo_url:e.target.value})} /></label><label className="check"><input type="checkbox" checked={user.is_professional} onChange={(e) => updateUser(index,{is_professional:e.target.checked})} /> Também atende clientes</label></div>{index>0 && <button type="button" className="text-link danger" onClick={() => setUsers(users.filter((_,item)=>item!==index))}>Remover</button>}</div>)}<button type="button" className="button-ghost" onClick={() => setUsers([...users,{name:"",username:"",password:password(),role:"PROFESSIONAL",is_professional:true,photo_url:"",active:true}])}>+ Adicionar profissional</button></div>}
    {step === 3 && <div><p className="eyebrow">3. Serviços</p><h2>Catálogo inicial</h2>{services.map((service,index) => <div className="repeater-card field-grid" key={index}><label>Nome<input value={service.name} onChange={(e)=>updateService(index,{name:e.target.value})} /></label><label>Preço (R$)<input inputMode="decimal" value={service.price} onChange={(e)=>updateService(index,{price:e.target.value})} /></label><label>Duração padrão<input type="number" min="5" step="5" value={service.duration_minutes} onChange={(e)=>updateService(index,{duration_minutes:Number(e.target.value)})} /></label>{services.length>1 && <button type="button" className="text-link danger" onClick={()=>setServices(services.filter((_,item)=>item!==index))}>Remover</button>}</div>)}<button type="button" className="button-ghost" onClick={()=>setServices([...services,{name:"",price:"",duration_minutes:60}])}>+ Adicionar serviço</button></div>}
    {step === 4 && <div><p className="eyebrow">4. Resumo</p><h2>Revise antes de criar</h2><div className="summary-box"><strong>{business.name}</strong><span>/{business.slug} · {categories.find(([value])=>value===business.business_type)?.[1]}</span><span>{users.length} usuários · {services.length} serviços</span>{users.map((user)=><code key={user.username}>{user.name}: {user.username}</code>)}</div><form action={action}><input type="hidden" name="payload" value={JSON.stringify(payload)} /><button className="button" disabled={pending}>{pending ? "Criando com segurança..." : "Criar estabelecimento"}</button></form></div>}
    <div className="wizard-actions">{step>1 && <button type="button" className="button-ghost" onClick={()=>setStep(step-1)}>Voltar</button>}{step<4 && <button type="button" className="button" onClick={()=>setStep(step+1)}>Continuar</button>}</div>
  </section>;
}
