import Link from "next/link";
import { addDays } from "date-fns";
import { formatInTimeZone } from "date-fns-tz";

type Appointment = { id: string; starts_at: string; status: string; customers: { name: string } | null; services: { name: string } | null; professionals: { name: string } | null };
type Block = { id: string; starts_at: string; reason: string | null; professionals: { name: string } | null };

export function WeeklyAgenda({ startDate, timezone, appointments, blocks, baseHref }: { startDate: string; timezone: string; appointments: Appointment[]; blocks: Block[]; baseHref: string }) {
  const days = Array.from({ length: 7 }, (_, index) => addDays(new Date(`${startDate}T12:00:00Z`), index));
  return <section className="week-card"><header><div><p className="eyebrow">Visão da semana</p><h2>{new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", timeZone: "UTC" }).format(days[0])} — {new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "long", timeZone: "UTC" }).format(days[6])}</h2></div><div className="date-nav"><Link href={`${baseHref}${formatInTimeZone(addDays(days[0], -7), "UTC", "yyyy-MM-dd")}`}>←</Link><Link href={`${baseHref}${formatInTimeZone(new Date(), timezone, "yyyy-MM-dd")}`}>Hoje</Link><Link href={`${baseHref}${formatInTimeZone(addDays(days[0], 7), "UTC", "yyyy-MM-dd")}`}>→</Link></div></header><div className="week-grid">{days.map((day) => { const date = formatInTimeZone(day, "UTC", "yyyy-MM-dd"); const items = appointments.filter((item) => formatInTimeZone(item.starts_at, timezone, "yyyy-MM-dd") === date); const dayBlocks = blocks.filter((item) => formatInTimeZone(item.starts_at, timezone, "yyyy-MM-dd") === date); return <article className="week-day" key={date}><div className="week-day-head"><span>{new Intl.DateTimeFormat("pt-BR", { weekday: "short", timeZone: "UTC" }).format(day)}</span><strong>{formatInTimeZone(day, "UTC", "dd")}</strong></div><div className="week-items">{items.map((item) => <Link href={`/painel/agendamentos/${item.id}`} className={`week-event status-${item.status.toLowerCase()}`} key={item.id}><time>{formatInTimeZone(item.starts_at, timezone, "HH:mm")}</time><strong>{item.customers?.name}</strong><small>{item.services?.name} · {item.professionals?.name}</small></Link>)}{dayBlocks.map((item) => <div className="week-event is-blocked" key={item.id}><time>{formatInTimeZone(item.starts_at, timezone, "HH:mm")}</time><strong>Bloqueado</strong><small>{item.reason || item.professionals?.name}</small></div>)}{!items.length && !dayBlocks.length && <p>Livre</p>}</div></article>; })}</div></section>;
}
